/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as KiplingMeadowsRouteImport } from './routes/kipling-meadows'
import { Route as KiplingRouteImport } from './routes/kipling'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamSlugRouteImport } from './routes/team_.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const KiplingMeadowsRoute = KiplingMeadowsRouteImport.update({
  id: '/kipling-meadows',
  path: '/kipling-meadows',
  getParentRoute: () => rootRouteImport,
} as any)
const KiplingRoute = KiplingRouteImport.update({
  id: '/kipling',
  path: '/kipling',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team_/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/kipling': typeof KiplingRoute
  '/kipling-meadows': typeof KiplingMeadowsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/kipling': typeof KiplingRoute
  '/kipling-meadows': typeof KiplingMeadowsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/kipling': typeof KiplingRoute
  '/kipling-meadows': typeof KiplingMeadowsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/team': typeof TeamRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/team_/$slug': typeof TeamSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/economics'
    | '/faq'
    | '/kipling'
    | '/kipling-meadows'
    | '/partners'
    | '/pricing'
    | '/process'
    | '/team'
    | '/blog/$slug'
    | '/team/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/economics'
    | '/faq'
    | '/kipling'
    | '/kipling-meadows'
    | '/partners'
    | '/pricing'
    | '/process'
    | '/team'
    | '/blog/$slug'
    | '/team/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/economics'
    | '/faq'
    | '/kipling'
    | '/kipling-meadows'
    | '/partners'
    | '/pricing'
    | '/process'
    | '/team'
    | '/blog_/$slug'
    | '/team_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  EconomicsRoute: typeof EconomicsRoute
  FaqRoute: typeof FaqRoute
  KiplingRoute: typeof KiplingRoute
  KiplingMeadowsRoute: typeof KiplingMeadowsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  ProcessRoute: typeof ProcessRoute
  TeamRoute: typeof TeamRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TeamSlugRoute: typeof TeamSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kipling-meadows': {
      id: '/kipling-meadows'
      path: '/kipling-meadows'
      fullPath: '/kipling-meadows'
      preLoaderRoute: typeof KiplingMeadowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kipling': {
      id: '/kipling'
      path: '/kipling'
      fullPath: '/kipling'
      preLoaderRoute: typeof KiplingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team_/$slug': {
      id: '/team_/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  EconomicsRoute: EconomicsRoute,
  FaqRoute: FaqRoute,
  KiplingRoute: KiplingRoute,
  KiplingMeadowsRoute: KiplingMeadowsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  ProcessRoute: ProcessRoute,
  TeamRoute: TeamRoute,
  BlogSlugRoute: BlogSlugRoute,
  TeamSlugRoute: TeamSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
