/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as KiplingMeadowsRouteImport } from './routes/kipling-meadows'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as DanielBessmertRouteImport } from './routes/daniel-bessmert'
import { Route as DanKatzmanRouteImport } from './routes/dan-katzman'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'

const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const KiplingMeadowsRoute = KiplingMeadowsRouteImport.update({
  id: '/kipling-meadows',
  path: '/kipling-meadows',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const DanielBessmertRoute = DanielBessmertRouteImport.update({
  id: '/daniel-bessmert',
  path: '/daniel-bessmert',
  getParentRoute: () => rootRouteImport,
} as any)
const DanKatzmanRoute = DanKatzmanRouteImport.update({
  id: '/dan-katzman',
  path: '/dan-katzman',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dan-katzman': typeof DanKatzmanRoute
  '/daniel-bessmert': typeof DanielBessmertRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/kipling-meadows': typeof KiplingMeadowsRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dan-katzman': typeof DanKatzmanRoute
  '/daniel-bessmert': typeof DanielBessmertRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/kipling-meadows': typeof KiplingMeadowsRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dan-katzman': typeof DanKatzmanRoute
  '/daniel-bessmert': typeof DanielBessmertRoute
  '/economics': typeof EconomicsRoute
  '/faq': typeof FaqRoute
  '/kipling-meadows': typeof KiplingMeadowsRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/contact'
    | '/dan-katzman'
    | '/daniel-bessmert'
    | '/economics'
    | '/faq'
    | '/kipling-meadows'
    | '/pricing'
    | '/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/contact'
    | '/dan-katzman'
    | '/daniel-bessmert'
    | '/economics'
    | '/faq'
    | '/kipling-meadows'
    | '/pricing'
    | '/process'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/contact'
    | '/dan-katzman'
    | '/daniel-bessmert'
    | '/economics'
    | '/faq'
    | '/kipling-meadows'
    | '/pricing'
    | '/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DanKatzmanRoute: typeof DanKatzmanRoute
  DanielBessmertRoute: typeof DanielBessmertRoute
  EconomicsRoute: typeof EconomicsRoute
  FaqRoute: typeof FaqRoute
  KiplingMeadowsRoute: typeof KiplingMeadowsRoute
  PricingRoute: typeof PricingRoute
  ProcessRoute: typeof ProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kipling-meadows': {
      id: '/kipling-meadows'
      path: '/kipling-meadows'
      fullPath: '/kipling-meadows'
      preLoaderRoute: typeof KiplingMeadowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daniel-bessmert': {
      id: '/daniel-bessmert'
      path: '/daniel-bessmert'
      fullPath: '/daniel-bessmert'
      preLoaderRoute: typeof DanielBessmertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dan-katzman': {
      id: '/dan-katzman'
      path: '/dan-katzman'
      fullPath: '/dan-katzman'
      preLoaderRoute: typeof DanKatzmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DanKatzmanRoute: DanKatzmanRoute,
  DanielBessmertRoute: DanielBessmertRoute,
  EconomicsRoute: EconomicsRoute,
  FaqRoute: FaqRoute,
  KiplingMeadowsRoute: KiplingMeadowsRoute,
  PricingRoute: PricingRoute,
  ProcessRoute: ProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
